// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8Eh-PcVLcLIKjHOXK42Ws2mQcBRGUgM',
    appId: '1:599618365697:web:0e760d359762d0f1d15300',
    messagingSenderId: '599618365697',
    projectId: 'miniature-adventure',
    authDomain: 'miniature-adventure.firebaseapp.com',
    storageBucket: 'miniature-adventure.firebasestorage.app',
    measurementId: 'G-34J23MZWVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcyEujbsZ1-xd_Ex6YkWLym0Ot8D7y4SM',
    appId: '1:599618365697:android:032b3665a97f7481d15300',
    messagingSenderId: '599618365697',
    projectId: 'miniature-adventure',
    storageBucket: 'miniature-adventure.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW2WeYXYD2NmAZ-M9qaYYGjcSNMWrm-QM',
    appId: '1:599618365697:ios:fc9fc644bc645536d15300',
    messagingSenderId: '599618365697',
    projectId: 'miniature-adventure',
    storageBucket: 'miniature-adventure.firebasestorage.app',
    iosBundleId: 'com.example.miniatureAdventure',
  );
}
